# Welcome to Jekyll!

# Website settings
title: Krishan's Resume
description: Krishan's resume, hosted on github pages!.
keywords: Krishan,resume,Jekyll,github,gh-pages
baseurl: /resume # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://KrishyV.github.io/resume # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author: # change following line to your infomation.
  name: Krishan # Be used at blog posts' author.
  first_name: Krishan # Be used at index page about me section.
  last_name: V # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg # upload your avatar at directory and edit it.
  github_username: KrishyV # Leave blank if you don't have now
  linkedin_id: krishanvj # Leave blank if you don't have now
  facebook_username: # Leave blank if you don't have now
  twitter_username:  # Leave blank if you don't have now
  email: krishanvj@pm.me # Leave blank if you don't have now
  cv: # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-database
    - name: fa-linux
  skill_icon2:
    - name: icon-reactjs
    - name: icon-aws
  desc: I am an undergraduate at the National University of Singapore with a passion for all things technology. I am a Mechanical Engineering student with 3 years of software development experience. I am always open to new opportunities to further hone my skills as a developer and build meaningful solutions to solve the needs of your business and community.
   # Describe yourself.

# comment
# disqus: # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#   name: jalpc

# analytics
## google analytics
# ga: # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
#   id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio: # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: on # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on # index page carousel switch
blog_carousel: on # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
